services:
  vexil-server:
    build:
      context: apps/vexil-server
      target: dev
    ports:
      - "8080-8099:8080"
    env_file:
      - path: apps/vexil-server/.env
        required: false
    volumes:
      - ./apps/vexil-server:/app
      - backend-go-mod-cache:/go/pkg/mod
      - backend-go-build-cache:/root/.cache/go-build

  vexil-frontend:
    build:
      context: apps/vexil-frontend
    ports:
      - "4321-4399:4321"
    env_file:
      - path: apps/vexil-frontend/.env
        required: false
    volumes:
      - ./apps/vexil-frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - vexil-server

  vexil-website:
    build:
      context: apps/vexil-website
    ports:
      - "4322-4399:4321"
    env_file:
      - path: apps/vexil-website/.env
        required: false
    volumes:
      - ./apps/vexil-website:/app
      - website-node-modules:/app/node_modules

volumes:
  backend-go-mod-cache:
  backend-go-build-cache:
  frontend-node-modules:
  website-node-modules:
