services:
  vexil-io:
    build:
      context: apps/vexil-io
      target: dev
    ports:
      - "6600:6600"
    env_file:
      - path: apps/vexil-io/.env
        required: false
    volumes:
      - ./apps/vexil-io:/app
      - backend-go-mod-cache:/go/pkg/mod
      - backend-go-build-cache:/root/.cache/go-build

  vexil-frontend:
    build:
      context: apps/vexil-frontend
    ports:
      - "6611:6611"
    env_file:
      - path: apps/vexil-frontend/.env
        required: false
    volumes:
      - ./apps/vexil-frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - vexil-io

  vexil-website:
    build:
      context: apps/vexil-website
    ports:
      - "6622:6622"
    env_file:
      - path: apps/vexil-website/.env
        required: false
    volumes:
      - ./apps/vexil-website:/app
      - website-node-modules:/app/node_modules

volumes:
  backend-go-mod-cache:
  backend-go-build-cache:
  frontend-node-modules:
  website-node-modules:
