load("@rules_nodejs//nodejs:defs.bzl", "js_library")
load("@aspect_rules_js//js:defs.bzl", "js_run_binary")

# Define the source files for the Astro project
filegroup(
    name = "srcs",
    srcs = glob(
        [
            "public/**/*",
            "src/**/*",
        ],
    ) + ["package.json",
        "astro.config.mjs",
        "tsconfig.json",
    ],
)

# # Build the Astro project
# # Unless deployed to production this is not useful during development
# # But I am keeping it just in case.
# js_run_binary(
#     name = "build",
#     srcs = [":srcs"],
#     args = ["build"],
#     tool = "//:node_modules/astro/bin/astro",
#     outs = ["dist"],
#     chdir = package_name(),
# )

# Serve the project for development
js_run_binary(
    name = "dev",
    srcs = [":srcs"],
    args = ["dev"],
    tool = "//:node_modules/astro/bin/astro",
    chdir = package_name(),
)

# Library target for visibility across the monorepo
js_library(
    name = "frontend",
    srcs = [":build"],
    visibility = ["//visibility:public"],
)
